version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ihm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ihm
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - ihm-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: ihm_mailpit
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - ihm-network

  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: wissemhajbi/ihm-api:latest
    container_name: ihm_api
    restart: unless-stopped
    depends_on:
      - db
      - mailpit
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/ihm?schema=public'
      APP_WEB_URL: 'http://localhost:3000'
    ports:
      - '3001:3001'
    networks:
      - ihm-network

networks:
  ihm-network:
    driver: bridge
