import { MailTemplateChannel } from '@prisma/client';

export type DefaultMailTemplate = {
  slug: string;
  name: string;
  description: string;
  trigger: string;
  channel: MailTemplateChannel;
  subject: string | null;
  body: string;
  recipients: string;
  type: string;
};

export const defaultMailTemplates: DefaultMailTemplate[] = [
  {
    slug: 'auth.welcome',
    name: 'Welcome Email',
    description: 'Sent after a new account is registered.',
    trigger: 'user.registered',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Welcome to VoyageHub, {{user_name}}',
    body: 'Hello {{user_name}},\n\nWelcome to VoyageHub. Your account is ready and you can now explore hotels, offers, and your booking dashboard.\n\nSign in here: {{login_url}}\n\nNeed help? Contact us at {{support_email}}.',
    recipients: 'client',
    type: 'success',
  },
  {
    slug: 'auth.reset-password',
    name: 'Reset Password',
    description: 'Secure password reset email.',
    trigger: 'auth.forgot_password',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Reset your VoyageHub password',
    body: 'Hello {{user_name}},\n\nWe received a request to reset your password. Use the secure link below to choose a new one:\n{{reset_url}}\n\nThis link expires in {{expires_in}}.\n\nIf you did not request this change, you can ignore this email.',
    recipients: 'client',
    type: 'warning',
  },
  {
    slug: 'auth.password-changed',
    name: 'Password Changed',
    description: 'Sent after a password is updated.',
    trigger: 'auth.password_changed',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Your VoyageHub password was changed',
    body: 'Hello {{user_name}},\n\nYour password was updated successfully on {{changed_at}}.\n\nIf you did not make this change, contact support immediately at {{support_email}}.',
    recipients: 'client',
    type: 'info',
  },
  {
    slug: 'reservation.confirmed',
    name: 'Booking Confirmation',
    description: 'Sent when a reservation becomes confirmed.',
    trigger: 'reservation.confirmed',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Booking confirmed for {{hotel_name}}',
    body: 'Hello {{user_name}},\n\nYour booking {{conf_code}} at {{hotel_name}} is confirmed.\n\nCheck-in: {{check_in}}\nCheck-out: {{check_out}}\nGuests: {{guests}}\nTotal: {{amount}}\n\nYou can review your booking here: {{action_url}}',
    recipients: 'client',
    type: 'success',
  },
  {
    slug: 'reservation.payment-receipt',
    name: 'Payment Receipt',
    description: 'Sent after a successful online payment.',
    trigger: 'reservation.payment_succeeded',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Payment receipt for booking {{conf_code}}',
    body: 'Hello {{user_name}},\n\nWe received your payment for {{hotel_name}}.\n\nBooking: {{conf_code}}\nTotal paid: {{amount}}\nTaxes: {{taxes}}\nRoom subtotal: {{room_subtotal}}\n\nYour booking details: {{action_url}}',
    recipients: 'client',
    type: 'success',
  },
  {
    slug: 'reservation.cancelled',
    name: 'Booking Cancellation',
    description: 'Sent when a booking is cancelled.',
    trigger: 'reservation.cancelled',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Booking {{conf_code}} has been cancelled',
    body: 'Hello {{user_name}},\n\nYour reservation at {{hotel_name}} has been cancelled.\n\nBooking: {{conf_code}}\nStay: {{check_in}} to {{check_out}}\n\nView details: {{action_url}}',
    recipients: 'client',
    type: 'danger',
  },
  {
    slug: 'reservation.refund-summary',
    name: 'Refund Summary',
    description: 'Sent after a cancellation with refund details.',
    trigger: 'reservation.refund_summary',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Refund summary for booking {{conf_code}}',
    body: 'Hello {{user_name}},\n\nHere is the refund summary for your cancelled reservation.\n\nBooking: {{conf_code}}\nRefund type: {{refund_type}}\nRefund amount: {{refund_amount}}\nCharge amount: {{charge_amount}}\nTotal paid: {{amount}}\n\nNeed help? Reply to {{support_email}}.',
    recipients: 'client',
    type: 'info',
  },
  {
    slug: 'reservation.checkin-reminder',
    name: 'Check-in Reminder',
    description: 'Sent 24 hours before check-in.',
    trigger: 'reservation.checkin_reminder',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Reminder: your check-in at {{hotel_name}} is coming up',
    body: 'Hello {{user_name}},\n\nThis is a reminder for your upcoming stay at {{hotel_name}}.\n\nCheck-in: {{check_in}}\nCheck-out: {{check_out}}\nBooking: {{conf_code}}\n\nOpen your reservation: {{action_url}}',
    recipients: 'client',
    type: 'info',
  },
  {
    slug: 'reservation.review-request',
    name: 'Post-stay Review Request',
    description: 'Sent after a stay is completed.',
    trigger: 'reservation.review_request',
    channel: MailTemplateChannel.EMAIL,
    subject: 'How was your stay at {{hotel_name}}?',
    body: 'Hello {{user_name}},\n\nWe hope you enjoyed your stay at {{hotel_name}}. We would love to hear your feedback.\n\nShare your review here: {{action_url}}\n\nBooking: {{conf_code}}',
    recipients: 'client',
    type: 'info',
  },
  {
    slug: 'promotion.new-destination',
    name: 'New Destination Alert',
    description: 'Sent when a new hotel is added.',
    trigger: 'hotel.created',
    channel: MailTemplateChannel.EMAIL,
    subject: 'New destination: {{hotel_name}}',
    body: 'Hello {{user_name}},\n\nA new hotel is now available in {{city}}.\n\nDiscover {{hotel_name}} here: {{action_url}}',
    recipients: 'client',
    type: 'success',
  },
  {
    slug: 'promotion.new-offer',
    name: 'New Offer Alert',
    description: 'Sent when a new offer is created.',
    trigger: 'offer.created',
    channel: MailTemplateChannel.EMAIL,
    subject: 'New special offer: {{offer_title}}',
    body: 'Hello {{user_name}},\n\nA new offer is now available{{hotel_name_clause}}.\n\nOffer: {{offer_title}}\nDiscount: {{discount}}\n\nExplore offers: {{action_url}}',
    recipients: 'client',
    type: 'success',
  },
  {
    slug: 'complaint.received',
    name: 'Complaint Received',
    description: 'Sent when a support request is created.',
    trigger: 'complaint.created',
    channel: MailTemplateChannel.EMAIL,
    subject: 'We received your support request #{{ticket_id}}',
    body: 'Hello {{user_name}},\n\nWe received your request about booking {{conf_code}}.\n\nSubject: {{subject}}\nTicket ID: {{ticket_id}}\nStatus: {{status}}\n\nOur team will get back to you soon.',
    recipients: 'client',
    type: 'warning',
  },
  {
    slug: 'complaint.updated',
    name: 'Complaint Updated',
    description: 'Sent when a complaint receives an update.',
    trigger: 'complaint.updated',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Update on support ticket #{{ticket_id}}',
    body: 'Hello {{user_name}},\n\nYour support ticket #{{ticket_id}} has been updated.\n\nStatus: {{status}}\nAgency response:\n{{agency_response}}\n\nYou can contact support at {{support_email}} if needed.',
    recipients: 'client',
    type: 'info',
  },
  {
    slug: 'complaint.closed',
    name: 'Complaint Closed',
    description: 'Sent when a complaint is closed.',
    trigger: 'complaint.closed',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Support ticket #{{ticket_id}} is now closed',
    body: 'Hello {{user_name}},\n\nYour support ticket #{{ticket_id}} has been closed.\n\nFinal response:\n{{agency_response}}',
    recipients: 'client',
    type: 'success',
  },
  {
    slug: 'ops.new-complaint-alert',
    name: 'New Complaint Alert',
    description: 'Internal alert for support teams.',
    trigger: 'complaint.created.internal',
    channel: MailTemplateChannel.EMAIL,
    subject: 'New complaint received: ticket #{{ticket_id}}',
    body: 'A new support request has been created.\n\nTicket ID: {{ticket_id}}\nBooking: {{conf_code}}\nCustomer: {{user_name}}\nSubject: {{subject}}\n\nOpen VoyageHub: {{action_url}}',
    recipients: 'admin',
    type: 'warning',
  },
  {
    slug: 'ops.new-hotel-alert',
    name: 'New Hotel Onboarding Alert',
    description: 'Internal alert for new hotels.',
    trigger: 'hotel.created.internal',
    channel: MailTemplateChannel.EMAIL,
    subject: 'New hotel onboarded: {{hotel_name}}',
    body: 'A new hotel has been added to VoyageHub.\n\nHotel: {{hotel_name}}\nCity: {{city}}\nContact: {{hotel_email}}\nPhone: {{hotel_phone}}',
    recipients: 'admin',
    type: 'info',
  },
  {
    slug: 'ops.payment-failure-alert',
    name: 'Payment Failure Alert',
    description: 'Internal alert when a payment fails.',
    trigger: 'payment.failed.internal',
    channel: MailTemplateChannel.EMAIL,
    subject: 'Payment failure for booking {{conf_code}}',
    body: 'A payment failure was received.\n\nBooking: {{conf_code}}\nCustomer: {{user_name}}\nHotel: {{hotel_name}}\nReason: {{failure_reason}}',
    recipients: 'admin',
    type: 'danger',
  },
  {
    slug: 'reservation.checkin-reminder.sms',
    name: 'SMS Check-in Reminder',
    description: 'SMS reminder template placeholder.',
    trigger: 'reservation.checkin_reminder',
    channel: MailTemplateChannel.SMS,
    subject: null,
    body: 'VoyageHub reminder: your stay at {{hotel_name}} starts on {{check_in}}. Booking {{conf_code}}.',
    recipients: 'client',
    type: 'sms',
  },
  {
    slug: 'reservation.confirmed.sms',
    name: 'SMS Booking Confirmation',
    description: 'SMS booking confirmation placeholder.',
    trigger: 'reservation.confirmed',
    channel: MailTemplateChannel.SMS,
    subject: null,
    body: 'VoyageHub: booking {{conf_code}} at {{hotel_name}} is confirmed. Check-in {{check_in}}.',
    recipients: 'client',
    type: 'sms',
  },
];
